### ISSUE TITLE
how to get user rating and comments from itc?

### ISSUE THREAD

**Issue by diaojunxian** [fedoco/itc-reporter#1]
@fedoco I had saw the itc-reporter,it is very useful,but I also need to get users rating and comments in itunes connect,how can I solve it ? Can you help me?

**Comment by fedoco** [comment]
Ratings are not available via official API - you would need to scrape them. https://github.com/grych/AppStoreReviews is an example of how to do that.

**Comment by diaojunxian** [comment]
@fedoco It is too older,so it did not work now.Were there other ways to slove my issue?

**Comment by fedoco** [comment]
I'm sorry, I cannot help you here. My script has nothing to do with user ratings. Why don't you ask the author of the script I mentioned instead?
