### ISSUE TITLE
Filter report by Apple Identifier 

### ISSUE THREAD

**Issue by glmanhtu** [fedoco/itc-reporter#12]
Hello,

I wonder if it has a way to get the report with filter by Apple Identifier?

**Comment by fedoco** [comment]
A quick look into the [documentation](https://help.apple.com/itc/appsreporterguide/) will give you the answer.

**Comment by glmanhtu** [comment]
Sorry but I already read the document again, but I still not found anything related to Apple Identifier. Maybe Apple doesn't provide this feature. 
Thanks
