### ISSUE TITLE
There is something wrong

### ISSUE THREAD

**Issue by kite8** [fedoco/itc-reporter#13]
My system is Win7;
python version: 2.7 with anaconda

```
runfile('D:/python/Web Crawler/ios/reporter.py', wdir='D:/python/Web Crawler/ios', args = '-u ***@***.com generateToken -P ***** --update-keychain-item "iTC Access Token"')
Your new access token has been generated.
AccessToken:7b7***b5-2813-4**6-8**5-1d9**51
Expiration Date:2018-03-04

Traceback (most recent call last):

  File "<ipython-input-2-2ca4d77b16ef>", line 1, in <module>
    runfile('D:/python/Web Crawler/ios/reporter.py', wdir='D:/python/Web Crawler/ios', args = '-u ***** generateToken -P ***** --update-keychain-item "iTC Access Token"')

  File "C:\ProgramData\Anaconda3\envs\trade\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\envs\trade\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/python/Web Crawler/ios/reporter.py", line 356, in <module>
    args.func(args)

  File "D:/python/Web Crawler/ios/reporter.py", line 113, in itc_generate_token
    keychain.set_generic_password(None, args.update_keychain_item, '', token)

NameError: global name 'keychain' is not defined
```

**Comment by fedoco** [comment]
Windows doesn't have Keychain, so you cannot use `--update-keychain-item`.

Also, please take care to not publish your iTunes login credentials in a public forum like GitHub – I have redacted your issue but as it has been public for some hours now you really should change your password.

**Comment by kite8** [comment]
Thank you very much~~~

**Comment by kite8** [comment]
@fedoco 
Thank you very much.
There is another question, when I run this code under ipython with spyder;
when I run the generate token command line, it will return the token info, but the spyder restart kernel immediately， so I can't store the token.

**Comment by kite8** [comment]
I need to  explain why I need to run the command under the spyder, not cmd.
I need to download the report everyday, and I have many apple id.
1.generate the token;
2.get accounts;
3.correct the report info(download the report -> unzip -> summarize data)

I need to store the token, and read it, then run the command.

**Comment by fedoco** [comment]
I meanwhile took the time to examine your business. Apparently, you are an App Store spammer whose accounts have been suspended by Apple several times in the past. I won't support your illegal activities and your idea of using my script for forging further Apple IDs. You're on your own here.

**Comment by kite8** [comment]
@fedoco  - - I think this is a mistake, I'm a staff member of a game publisher. So my company have many apple id- -.
