### ISSUE TITLE
FX rate?

### ISSUE THREAD

**Issue by xinquanatcolezhu** [fedoco/itc-reporter#15]
This is a great tool. any plan to add the function to download the payment report which include the FX rate?

**Comment by fedoco** [comment]
As this would require scraping the iTunes Connect web page: Sorry, no.

**Comment by xinquanatcolezhu** [comment]
hmm. i see. but how come the other reports do not need the scripting. any difference between these reports?

**Comment by fedoco** [comment]
It is unclear why Apple hasn't added access to the report containing FX rates to Reporter's API.
