### ISSUE TITLE
Use the Tool with Windows

### ISSUE THREAD

**Issue by Citymen2000** [fedoco/itc-reporter#16]
I´m getting a error message and i have no idea why. Maybe you can help me?

python reporter.py -u xxxxxxx generateToken -P xxxxxxxx
  File "reporter.py", line 111
    if not args.mode == 'Robot.XML': print "Keychain has been updated."
                                                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(if not args.mode == 'Robot.XML': print "Keychain has been updated.")?

**Comment by fedoco** [comment]
You need to use Python 2 instead of Python 3.

**Comment by Citymen2000** [comment]
Great, that works. Thank you!
