### ISSUE TITLE
Is itc reporter is down?

### ISSUE THREAD

**Issue by shiran1989** [fedoco/itc-reporter#18]
Hello. 
Is the service is down?
Since this morning we get 502 error (Bad Gateway) in the requests.
Thanks!

**Comment by desource90** [comment]
Also getting a 502 error since this morning, did something change with Apple's reporter API?

**Comment by fedoco** [comment]
502 indicates a temporary issue, so please retry. Right now the endpoint is reporting "Sales and Trends Reporter is currently available."

**Comment by shiran1989** [comment]
Thanks. It works now
