### ISSUE TITLE
Not getting a valid response ...... any ideas?

### ISSUE THREAD

**Issue by damienkilgannon** [fedoco/itc-reporter#2]
$ ./reporter.py -u {USERNAME} -p "{PASSWORD}" getSalesReport {VND_NUMBER} Daily 20161125

.<html>
.<head><title>403 Forbidden</title></head>
.<body bgcolor="white">
.<center><h1>403 Forbidden</h1></center>
.<hr><center>Shield</center>
.</body>
.</html>

seems to have been a problem with with url .... "https://reportingitc-reporter.apple.com" by added '-sh' the reporter.jar works again "https://reportingitc-reporter-sh.apple.com" .... but this fix does not resolve the problem when using this itc-reporter script

**Comment by fedoco** [comment]
"403 Forbidden" sometimes occurs when iTunes Connect is temporarily not available for whatever reason. Please simply try again later. It is working for me right now by the way.

**Comment by damienkilgannon** [comment]
thanks for replying, been messing with it all day, I can get valid responses using the reporter.jar and it itc-reporter working fine for you than it must be an issue with my credentials ...... are using using it with '-sh' in the URL?

**Comment by fedoco** [comment]
No, switching the URL shouldn't be necessary. Please double-check your credentials and don't forget that the `-p` option expects the password in the keychain (maybe try `-P` instead).

**Comment by damienkilgannon** [comment]
without '-sh' in URL i get 503 .... $ ./reporter.py -u me@email.com -P password getAccounts Sales

"HTTP Error 503. Did you choose reasonable query arguments?"

Credentials are all ok ... I am out of ideas :/

**Comment by fedoco** [comment]
Don't forget to specify the `-a` parameter (see "Querying accessible accounts" in the README).

**Comment by damienkilgannon** [comment]
i thought I shouldn't need -a when using getAccounts command? ....

**Comment by fedoco** [comment]
Indeed, you don't need `-a` when using getAccounts. The only thing left I can think of is that maybe your password contains special characters that don't get escaped properly in line 77 of the script. May that be the case?

**Comment by damienkilgannon** [comment]
**Update**: so when running the itc-reporter through my office network it was not working, however when I connected my laptop to my mobile hotspot it worked fine. It appears either itunes/apple were blocking my office IP or office firewall was causing issues. Funnily, during this time the reporter.jar worked fine retrieving reports satisfactorily (**BUT only when using '-sh' in sales URL**). Thankfully, I am back on track again but I have more questions than answers.

**Comment by fedoco** [comment]
Well, iTunes Connect is known to be full of wonders… Glad it worked out!

**Comment by damienkilgannon** [comment]
@fedoco ... back to square one again. Connection is been refused (403 forbidden), this time on my personnel and work networks and through a proxy. Are you experiencing similar?

**Comment by damienkilgannon** [comment]
@fedoco I see that Reporter.jar is now on v2.0 ..... what ever changes made to Reporter.jar need to be reflected in itc_reporter I am guessing.

**Comment by mikebarlow** [comment]
Just to jump in here. I'm the owner of a PHP implement for this and I'm experiencing the same issues with my PHP package. Everything works fine with the reporter.jar file but 403 errors with my package. Setting -sh to the URL doesn't do anything either!

Also for reference, I spent some time decompiling all the latest files in the .jar and from what I could see, with the main script although it was increased to 2.0 the major changes seemed to be that they supported some unzipping when downloading the reports now rather then just downloading the file straight into the working directory.

**Comment by damienkilgannon** [comment]
@mikebarlow good to know I am not going crazy ..... yes, they were the only changes which I found in v2.0 java code also, no reason to cause this python or your PHP code to fail! Not sure whats happening, not familiar with Jetty or Java.

**Comment by Alexxz** [comment]
Yesterday we have managed to fix own PHP implementation by setting the same
User-Agent header as Java does

8 Дек 2016 г. 1:47 пользователь "damienkilgannon" <notifications@github.com>
написал:

**Comment by mikebarlow** [comment]
@Alexxz I could have sworn I tried that but didn't think it worked, what had you got in your user agent line?

**Comment by Alexxz** [comment]
@mikebarlow  `[CURLOPT_USERAGENT => 'Java/1.8.0_92']`

**Comment by mikebarlow** [comment]
@Alexxz awesome thank you. Will give this a try when I get into the office later!

**Comment by Alexxz** [comment]
@mikebarlow there are headers we have sniffed from original client on our server.
```
Content-Type : application/x-www-form-urlencoded
User-Agent : Java/1.8.0_92
Host : our.proxy.addr
Accept : text/html, image/gif, image/jpeg, ; q=.2, /*; q=.2
Connection : keep-alive
Content-Length : 339

jsonRequest={"mode":"Robot.xml","password":"....
```

**Comment by damienkilgannon** [comment]
@Alexxz after adding those headers I don't get 403 anymore, but instead I am now getting 406 error.

**Comment by Alexxz** [comment]
I put all headers just as reference values of what we catched. Try only
user agent one. Did not you copied content length header accidentally?

**Comment by fedoco** [comment]
It was the missing `Accept` field only that made iTunes Connect so picky. I had to adjust it before adding, though.
Thanks for investigating!

**Comment by damienkilgannon** [comment]
@fedoco @Alexxz back working now with that fix, thanks for the help.

**Comment by ArashKeshmirian** [comment]
Thanks so much for this tool;  I'm getting "HTTP Error 504. Did you choose reasonable query arguments?", and I'm pretty sure my input is valid.

**Comment by mikebarlow** [comment]
Accept and User-Agent headers were the ones that did the trick for me.
For the Accept field I simply added text/plain, text/xml.

Thanks for the assistance!
