### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by chase-calm** [fedoco/itc-reporter#20]
Hey,

I want to use Python3 with this library.

I have made all the changes locally and it seems to work for me.

Can you give me access to push branches so I can make a pull request? @fedoco

**Comment by fedoco** [comment]
You don't need special access to the repo in order to make a pull request. You just need to [fork](https://gist.github.com/MarcDiethelm/7303312) it.

**Comment by fedoco** [comment]
Are you still interested?
