### ISSUE TITLE
getSubscriberReport cannot recognize date entry

### ISSUE THREAD

**Issue by josephpcowell** [fedoco/itc-reporter#26]
Thank you so much for creating this Java-less solution.

However, I am having an issue with the getSubscriberReport method. My goal is to retrieve subscriber data daily for a Podcast.

My code for the getSalesReport works just fine

`./reporter.py -u username@apple-id.com -a ACCOUNTNUM getSalesReport VENDORID Daily 20230103 -T TOKEN`

Returns `There were no sales for the date specified.`

But when I attempt to access the **getSusbcriberReport**, I run into a few issues.

1. By simply replacing getSalesReport, I get this output.

INPUT: `./reporter.py -u username@apple-id.com -a ACCOUNT_NUM getSubscriberReport VENDOR_ID Daily 20230103 -T TOKEN`

OUTPUT:
```
usage: reporter.py [-h] [-a ACCOUNT] [-m {Normal,Robot.XML}] -u USERID
                   {getStatus,getAccounts,getVendors,getVendorsAndRegions,getReportVersion,getFinancialReport,getSalesReport,getSubscriptionReport,getSubscriptionEventReport,getSubscriberReport,getNewsstandReport,getOptInReport,getPreOrderReport,generateToken,viewToken,deleteToken}
                   ...
reporter.py: error: unrecognized arguments: 20230103
```

2. I tried to leave out the date to see what would happen, and get a different error:

INPUT: `./reporter.py -u username[@apple-id.com] -a ACCOUNT_NUM getSubscriberReport VENDOR_ID Daily -T TOKEN`

OUTPUT: `Invalid date.`

I've successfully retrieved this report using the Reporter download and CLI, however, I'm trying to automate this report in a Python environment. Are there any major errors I am making in my code? Is there an issue with this specific method?

Thanks

**Comment by fedoco** [comment]
First of all thank you for your clear, thoughtful bug report. Regarding the issue: Have you tried `getSubscriberReport <VENDOR_ID> <DATE>` yet, i.e. omitting `Daily`?

**Comment by josephpcowell** [comment]
Unfortunately, that didn't work either

INPUT: `./reporter.py -u username@apple-id.com -a ACCOUNT_NUM getSubscriberReport VENDOR_ID 20230103 -T TOKEN`

OUTPUT: `Invalid vendor number`

And for reference, this is the code that I am running with the Reporter app from Apple. 

INPUT: `java -jar Reporter.jar p=Reporter.properties Sales.getReport VENDORID, apSubscriptionsSnapshot, Summary, Daily, 20230103`

OUTPUT: `Successfully downloaded ApplePodcasts_SubscriptionSnapshot_VENDORID_20230103.txt.gz`

**Comment by josephpcowell** [comment]
Thank you @fedoco!

So, I did what you suggested, but got an error regarding the version number (`The version parameter you have specified is invalid. The latest version for this report is 1_0.`)

I decided just to remove version number, and it ended up working.

New code in `reporter.py`:
```
def itc_get_subscriber_report(args):
    command = "Sales.getReport, {0},apSubscriptionsSnapshot,Summary,Daily,{1}".format(
        args.vendor, args.date
    )
    output_result(post_request(ENDPOINT_SALES, get_credentials(args), command))
```

INPUT: `./reporter.py -u username@apple-id.com -a [ACCOUNT_NUM] getSubscriberReport [VENDOR_ID] 20230103 -T [TOKEN]`

OUTPUT: `Successfully downloaded ApplePodcasts_SubscriptionSnapshot_VENDORID_20230103.txt`

**Comment by fedoco** [comment]
Okay, I'll add this new report type shortly to the script then. Thanks for your help pointing out and debugging the issue!

**Comment by fedoco** [comment]
Had a chance to fix it right now. Could you please pull the newest version and test the newly added parameter as follows:

`./reporter.py -u username@apple-id.com -a [ACCOUNT_NUM] getPodcastsSubscriptionSnapshotReport [VENDOR_ID] 20230103 -T [TOKEN]`

**Comment by josephpcowell** [comment]
Worked perfectly 👍 

Greatly appreciate the support!

**Comment by fedoco** [comment]
Thanks!

**Comment by fedoco** [comment]
Thanks!
