### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by jakob** [fedoco/itc-reporter#3]
Hi!

Thanks for providing this tool! This will come in handy when Apple finally turns off the old autoingestion API.

I currently use curl to download sales reports.

I'm looking for the documentation for the JSON API that Reporter talks to. `reporter.py` is reasonable readable, but ideally I'm looking for some real docs. How did you find out how the API works?

Does Apple provide documentation for the JSON API?

Did you reverse engineer Reporter?

Best regards,
Jakob

**Comment by fedoco** [comment]
I'm afraid there is no official API documentation (at least none that I'm aware of).
I intercepted HTTP calls of Apple's Reporter to find out how it works: It's really not that hard and I'm sure that reading the code of my script will give you an idea of the API's workings very quickly.

**Comment by jakob** [comment]
OK. Thanks for letting me know!
