### ISSUE TITLE
HTTP Error 504

### ISSUE THREAD

**Issue by ArashKeshmirian** [fedoco/itc-reporter#5]
This is an awesome project!

However, I can't seem to figure out what's going on here... I keep getting HTTP Error 504 when trying to download a financial report:

`./reporter.py -u abc@xyz.com -p "iTC Access" -a 219903 getFinancialReport 80092992 US 2016 01`
`HTTP Error 504. Did you choose reasonable query arguments?`

I'm able to `getStatus`, etc, and have tried changing the server to add -sh to the URL per some other recommendations.

**Comment by damienkilgannon** [comment]
Are trying to grab password from keychain or not?

**Comment by ArashKeshmirian** [comment]
Yep, using -p to pull password from keychain. I've verified this works by putting a bogus password in the keychain entry; I get a password error then.

**Comment by fedoco** [comment]
@ArashKeshmirian Have you made sure the iTunes Connect account you're using is allowed to retrieve financial reports?

**Comment by ArashKeshmirian** [comment]
Yeah, checked that too.  We’ve been using it for appfigures / AutoIngestion for years.

—arash

**Comment by fedoco** [comment]
Hmm. Does Apple's official Reporter tool work for you right now?

**Comment by ArashKeshmirian** [comment]
Sort of.  Here's the transcript there (anonymized).  I've tried at the office and at home with the same results:
```
$ java -jar Reporter.jar p=Reporter.properties Finance.getStatus
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Status>
    <Code>0</Code>
    <Message>Finance Reporter is currently available.</Message>
</Status>

$ java -jar Reporter.jar p=Reporter.properties Finance.getAccounts
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Accounts>
    <Account>
        <Name>Company, Inc.</Name>
        <Number>123456</Number>
    </Account>
</Accounts>

$ java -jar Reporter.jar p=Reporter.properties Finance.getVendorsAndRegions
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>111</Code>
  <Message>Network is available but cannot connect to application. Check your proxy and firewall settings and try again.</Message>
</Error>

**Comment by fedoco** [comment]
As stated in the error message, this implies that you're facing a general problem with your connection that doesn't seem directly related to my Python script. I would therefore suggest to reach out to [Apple's developer support](https://developer.apple.com/contact/) in order to sort out the issue. Sorry.

**Comment by fedoco** [comment]
I just found a possible cause for the problem you're experiencing: https://forums.developer.apple.com/thread/65994
Could it be possible that some component in your connection somehow still cached the invalid SSL certificate from weeks ago?

**Comment by ArashKeshmirian** [comment]
I'm running this on a fresh new MacBook Pro, so that seems unlikely, but I will investigate.  Thanks for the troubleshooting, @fedoco.

**Comment by damienkilgannon** [comment]
@arash maybe try using Mitmproxy (https://github.com/mitmproxy/mitmproxy)
to sniff the HTTPS packets and double check the headers and the ssl cert
been sent ...
